name = "xinghemulu"
main = "worker.js"
compatibility_date = "2024-03-24"

[[d1_databases]]
binding = "DB"
database_name = "xinghemulu"
database_id = "b4cb638c-a503-43be-9df6-e4396f2bfcdd"

[[services]]
binding = "ASSETS"
service = "xinghemulu"

[site]
bucket = "./public"
assets_path = "./public" 